package models

// CurrencyCode which is viable as of 10-Apr-2024
// see https://www.iban.com/currency-codes
type CurrencyCode string

const (
	AFN CurrencyCode = "AFN" // Afghan Afghani
	ALL CurrencyCode = "ALL" // Albanian Lek
	DZD CurrencyCode = "DZD" // Algerian Dinar
	USD CurrencyCode = "USD" // United States Dollar
	EUR CurrencyCode = "EUR" // Euro
	AOA CurrencyCode = "AOA" // Angolan Kwanza
	XCD CurrencyCode = "XCD" // East Caribbean Dollar
	ARS CurrencyCode = "ARS" // Argentine Peso
	AMD CurrencyCode = "AMD" // Armenian Dram
	AWG CurrencyCode = "AWG" // Aruban Florin
	AUD CurrencyCode = "AUD" // Australian Dollar
	AZN CurrencyCode = "AZN" // Azerbaijani Manat
	BSD CurrencyCode = "BSD" // Bahamian Dollar
	BHD CurrencyCode = "BHD" // Bahraini Dinar
	BDT CurrencyCode = "BDT" // Bangladeshi Taka
	BBD CurrencyCode = "BBD" // Barbadian Dollar
	BYN CurrencyCode = "BYN" // Belarusian Ruble
	XOF CurrencyCode = "XOF" // West African CFA franc
	BMD CurrencyCode = "BMD" // Bermudian Dollar
	BTN CurrencyCode = "BTN" // Bhutanese Ngultrum
	INR CurrencyCode = "INR" // Indian Rupee
	BOB CurrencyCode = "BOB" // Bolivian Boliviano
	BOV CurrencyCode = "BOV" // Bolivian Mvdol
	BAM CurrencyCode = "BAM" // Bosnia and Herzegovina Convertible Mark
	BWP CurrencyCode = "BWP" // Botswana Pula
	NOK CurrencyCode = "NOK" // Norwegian Krone
	BRL CurrencyCode = "BRL" // Brazilian Real
	BND CurrencyCode = "BND" // Brunei Dollar
	BGN CurrencyCode = "BGN" // Bulgarian Lev
	BIF CurrencyCode = "BIF" // Burundian Franc
	CVE CurrencyCode = "CVE" // Cape Verdean Escudo
	KHR CurrencyCode = "KHR" // Cambodian Riel
	XAF CurrencyCode = "XAF" // Central African CFA franc
	CAD CurrencyCode = "CAD" // Canadian Dollar
	KYD CurrencyCode = "KYD" // Cayman Islands Dollar
	CLF CurrencyCode = "CLF" // Unidad de Fomento
	CLP CurrencyCode = "CLP" // Chilean Peso
	CNY CurrencyCode = "CNY" // Chinese Yuan
	COP CurrencyCode = "COP" // Colombian Peso
	COU CurrencyCode = "COU" // Unidad de Valor Real
	KMF CurrencyCode = "KMF" // Comoro Franc
	CDF CurrencyCode = "CDF" // Congolese Franc
	NZD CurrencyCode = "NZD" // New Zealand Dollar
	CRC CurrencyCode = "CRC" // Costa Rican Colón
	HRK CurrencyCode = "HRK" // Croatian Kuna
	CUP CurrencyCode = "CUP" // Cuban Peso
	CUC CurrencyCode = "CUC" // Cuban Convertible Peso
	ANG CurrencyCode = "ANG" // Netherlands Antillean Guilder
	CZK CurrencyCode = "CZK" // Czech Koruna
	DKK CurrencyCode = "DKK" // Danish Krone
	DJF CurrencyCode = "DJF" // Djiboutian Franc
	DOP CurrencyCode = "DOP" // Dominican Peso
	EGP CurrencyCode = "EGP" // Egyptian Pound
	SVC CurrencyCode = "SVC" // Salvadoran Colón
	ERN CurrencyCode = "ERN" // Eritrean Nakfa
	ETB CurrencyCode = "ETB" // Ethiopian Birr
	FKP CurrencyCode = "FKP" // Falkland Islands Pound
	FJD CurrencyCode = "FJD" // Fijian Dollar
	XPF CurrencyCode = "XPF" // CFP franc
	GMD CurrencyCode = "GMD" // Gambian Dalasi
	GEL CurrencyCode = "GEL" // Georgian Lari
	GHS CurrencyCode = "GHS" // Ghanaian Cedi
	GIP CurrencyCode = "GIP" // Gibraltar Pound
	GTQ CurrencyCode = "GTQ" // Guatemalan Quetzal
	GBP CurrencyCode = "GBP" // British Pound
	GNF CurrencyCode = "GNF" // Guinean Franc
	GYD CurrencyCode = "GYD" // Guyanese Dollar
	HTG CurrencyCode = "HTG" // Haitian Gourde
	HNL CurrencyCode = "HNL" // Honduran Lempira
	HKD CurrencyCode = "HKD" // Hong Kong Dollar
	HUF CurrencyCode = "HUF" // Hungarian Forint
	ISK CurrencyCode = "ISK" // Icelandic Króna
	IDR CurrencyCode = "IDR" // Indonesian Rupiah
	XDR CurrencyCode = "XDR" // Special Drawing Rights
	IRR CurrencyCode = "IRR" // Iranian Rial
	IQD CurrencyCode = "IQD" // Iraqi Dinar
	ILS CurrencyCode = "ILS" // Israeli New Shekel
	JMD CurrencyCode = "JMD" // Jamaican Dollar
	JPY CurrencyCode = "JPY" // Japanese Yen
	JOD CurrencyCode = "JOD" // Jordanian Dinar
	KZT CurrencyCode = "KZT" // Kazakhstani Tenge
	KES CurrencyCode = "KES" // Kenyan Shilling
	KPW CurrencyCode = "KPW" // North Korean Won
	KRW CurrencyCode = "KRW" // South Korean Won
	KWD CurrencyCode = "KWD" // Kuwaiti Dinar
	KGS CurrencyCode = "KGS" // Kyrgyzstani Som
	LAK CurrencyCode = "LAK" // Lao Kip
	LBP CurrencyCode = "LBP" // Lebanese Pound
	LSL CurrencyCode = "LSL" // Lesotho Loti
	ZAR CurrencyCode = "ZAR" // South African Rand
	LRD CurrencyCode = "LRD" // Liberian Dollar
	LYD CurrencyCode = "LYD" // Libyan Dinar
	CHF CurrencyCode = "CHF" // Swiss Franc
	MOP CurrencyCode = "MOP" // Macanese Pataca
	MKD CurrencyCode = "MKD" // Macedonian Denar

	MGA CurrencyCode = "MGA" // Malagasy Ariary
	MWK CurrencyCode = "MWK" // Malawian Kwacha
	MYR CurrencyCode = "MYR" // Malaysian Ringgit
	MVR CurrencyCode = "MVR" // Maldivian Rufiyaa
	MRO CurrencyCode = "MRO" // Mauritanian Ouguiya
	MUR CurrencyCode = "MUR" // Mauritian Rupee
	MXN CurrencyCode = "MXN" // Mexican Peso
	MXV CurrencyCode = "MXV" // Mexican Unidad de Inversion (UDI)
	MDL CurrencyCode = "MDL" // Moldovan Leu
	MNT CurrencyCode = "MNT" // Mongolian Tugrik
	MAD CurrencyCode = "MAD" // Moroccan Dirham
	MZN CurrencyCode = "MZN" // Mozambican Metical
	MMK CurrencyCode = "MMK" // Myanmar Kyat
	NAD CurrencyCode = "NAD" // Namibian Dollar
	NPR CurrencyCode = "NPR" // Nepalese Rupee
	NIO CurrencyCode = "NIO" // Nicaraguan Córdoba
	NGN CurrencyCode = "NGN" // Nigerian Naira
	OMR CurrencyCode = "OMR" // Omani Rial
	PKR CurrencyCode = "PKR" // Pakistani Rupee
	PAB CurrencyCode = "PAB" // Panamanian Balboa
	PGK CurrencyCode = "PGK" // Papua New Guinean Kina
	PYG CurrencyCode = "PYG" // Paraguayan Guarani
	PEN CurrencyCode = "PEN" // Peruvian Nuevo Sol
	PHP CurrencyCode = "PHP" // Philippine Peso
	PLN CurrencyCode = "PLN" // Polish Zloty
	QAR CurrencyCode = "QAR" // Qatari Rial
	RON CurrencyCode = "RON" // Romanian Leu
	RUB CurrencyCode = "RUB" // Russian Ruble
	RWF CurrencyCode = "RWF" // Rwandan Franc
	SHP CurrencyCode = "SHP" // Saint Helena Pound
	WST CurrencyCode = "WST" // Samoan Tala
	STD CurrencyCode = "STD" // São Tomé and Príncipe Dobra
	SAR CurrencyCode = "SAR" // Saudi Riyal
	RSD CurrencyCode = "RSD" // Serbian Dinar
	SCR CurrencyCode = "SCR" // Seychellois Rupee
	SLL CurrencyCode = "SLL" // Sierra Leonean Leone
	SGD CurrencyCode = "SGD" // Singapore Dollar
	SBD CurrencyCode = "SBD" // Solomon Islands Dollar
	SOS CurrencyCode = "SOS" // Somali Shilling
	SSP CurrencyCode = "SSP" // South Sudanese Pound
	LKR CurrencyCode = "LKR" // Sri Lankan Rupee
	SDG CurrencyCode = "SDG" // Sudanese Pound
	SRD CurrencyCode = "SRD" // Surinamese Dollar
	SZL CurrencyCode = "SZL" // Swazi Lilangeni
	SEK CurrencyCode = "SEK" // Swedish Krona
	SYP CurrencyCode = "SYP" // Syrian Pound
	TWD CurrencyCode = "TWD" // New Taiwan Dollar
	TJS CurrencyCode = "TJS" // Tajikistani Somoni
	TZS CurrencyCode = "TZS" // Tanzanian Shilling
	THB CurrencyCode = "THB" // Thai Baht
	TOP CurrencyCode = "TOP" // Tongan Paʻanga
	TTD CurrencyCode = "TTD" // Trinidad and Tobago Dollar
	TND CurrencyCode = "TND" // Tunisian Dinar
	TRY CurrencyCode = "TRY" // Turkish Lira
	TMT CurrencyCode = "TMT" // Turkmenistani Manat
	UGX CurrencyCode = "UGX" // Ugandan Shilling
	UAH CurrencyCode = "UAH" // Ukrainian Hryvnia
	UYU CurrencyCode = "UYU" // Uruguayan Peso
	UYI CurrencyCode = "UYI" // Uruguayan Peso en Unidades Indexadas
	UZS CurrencyCode = "UZS" // Uzbekistan Som
	VUV CurrencyCode = "VUV" // Vanuatu Vatu
	VEF CurrencyCode = "VEF" // Venezuelan Bolívar
	VND CurrencyCode = "VND" // Vietnamese Dong
	YER CurrencyCode = "YER" // Yemeni Rial
	ZMW CurrencyCode = "ZMW" // Zambian Kwacha
	ZWL CurrencyCode = "ZWL" // Zimbabwean Dollar
)

// CurrencyModel represents a currency model
type Currency struct {
	Code   string `json:"code"`   // The code of the currency
	Name   string `json:"name"`   // The name of the currency
	Symbol string `json:"symbol"` // The symbol of the currency
}
